### ISSUE TITLE
Handle queries that don't return any results

### ISSUE THREAD

**Issue by txdao** [jedbrooke/cis41b-final-project#4]
See data.py

**Comment by txdao** [comment]
We might have to look into this together. I can catch this case if it shows up, so GUI needs to handle an empty generator somehow.

**Comment by jedbrooke** [comment]
maybe return False or None instead of a generator, and then I can check for that

**Comment by txdao** [comment]
Ok, I'll have it return False.

**Comment by txdao** [comment]
@jedbrooke Updated and pushed the db code.

**Comment by txdao** [comment]
Just tested. Works.
